const mockProductos = [
    { "category": "ABARROTES", "descripcion": "ACEITE DE AJONJOLI", "unidad": "BOT", "itemsPerUnit": 1 },
    { "category": "ABARROTES", "descripcion": "ACEITE DE OLIVA", "unidad": "BOT", "itemsPerUnit": 1 },
    { "category": "ABARROTES", "descripcion": "ACEITE MONTESOL X 18 Lt.", "unidad": "LATA", "itemsPerUnit": 1 },
    { "category": "ABARROTES", "descripcion": "ANÍS x 100", "unidad": "CAJA", "itemsPerUnit": 100 },
    { "category": "ABARROTES", "descripcion": "ARROZ x 50", "unidad": "SACO", "itemsPerUnit": 50 },
    { "category": "ABARROTES", "descripcion": "AZÚCAR BLANCA x 50", "unidad": "SACO", "itemsPerUnit": 50 },
    { "category": "ABARROTES", "descripcion": "AZÚCAR RUBIA x 50", "unidad": "SACO", "itemsPerUnit": 50 },
    { "category": "ABARROTES", "descripcion": "AZÚCAR SACHET x 500", "unidad": "PQT", "itemsPerUnit": 500 },
    { "category": "ABARROTES", "descripcion": "CAFÉ GRANEL x 1", "unidad": "BOLSA", "itemsPerUnit": 1 },
    { "category": "ABARROTES", "descripcion": "GUANTES DE CUERO", "unidad": "PAR", "itemsPerUnit": 2 },
    { "category": "ABARROTES", "descripcion": "HUEVO", "unidad": "UND", "itemsPerUnit": 1 },
    { "category": "ABARROTES", "descripcion": "KETCHUP GRANEL x 2", "unidad": "CAJA", "itemsPerUnit": 2 },
    { "category": "ABARROTES", "descripcion": "KETCHUP SACHET x 250", "unidad": "CAJA", "itemsPerUnit": 250 },
    { "category": "ABARROTES", "descripcion": "LECHE EVAPORADA x 24", "unidad": "PLANCHA", "itemsPerUnit": 24 },
    { "category": "ABARROTES", "descripcion": "LIGAS", "unidad": "CAJA", "itemsPerUnit": 1 },
    { "category": "ABARROTES", "descripcion": "LIGAS DE POLLO", "unidad": "PQT", "itemsPerUnit": 1 },
    { "category": "ABARROTES", "descripcion": "LIGAS DE POLLO x 1000", "unidad": "PQT", "itemsPerUnit": 1000 },
    { "category": "ABARROTES", "descripcion": "MANZANILLA x 100 und.", "unidad": "CAJA", "itemsPerUnit": 100 },
    { "category": "ABARROTES", "descripcion": "MOSTAZA GRANEL x 2", "unidad": "CAJA", "itemsPerUnit": 2 },
    { "category": "ABARROTES", "descripcion": "MOSTAZA SACHET x 250", "unidad": "CAJA", "itemsPerUnit": 250 },
    { "category": "ABARROTES", "descripcion": "PAPEL MANTECA", "unidad": "PQT", "itemsPerUnit": 1 },
    { "category": "ABARROTES", "descripcion": "PIMIENTA NEGRA", "unidad": "FRASCO", "itemsPerUnit": 1 },
    { "category": "ABARROTES", "descripcion": "PIÑA EN CONSERVA", "unidad": "LATA", "itemsPerUnit": 1 },
    { "category": "ABARROTES", "descripcion": "SAL x 25", "unidad": "SACO", "itemsPerUnit": 25 },
    { "category": "ABARROTES", "descripcion": "SALSA BBQ", "unidad": "BOT", "itemsPerUnit": 1 },
    { "category": "ABARROTES", "descripcion": "SERVILLETAS", "unidad": "PQT", "itemsPerUnit": 1 },
    { "category": "ABARROTES", "descripcion": "SODA CAUSTICA ESCAMAS", "unidad": "KG", "itemsPerUnit": 1 },
    { "category": "ABARROTES", "descripcion": "SORBETE ESPECIAL PLANCHA", "unidad": "PQT", "itemsPerUnit": 1 },
    { "category": "ABARROTES", "descripcion": "TÉ x 100", "unidad": "CAJA", "itemsPerUnit": 100 },
    { "category": "BEBIDAS", "descripcion": "AGUA MINERAL 3 LITROS x 4", "unidad": "PQT", "itemsPerUnit": 4 },
    { "category": "BEBIDAS", "descripcion": "AGUA SAN LUIS CON GAS 600 ML x 15", "unidad": "PQT", "itemsPerUnit": 15 },
    { "category": "BEBIDAS", "descripcion": "AGUA SAN LUIS SIN GAS 600 ML x 15", "unidad": "PQT", "itemsPerUnit": 15 },
    { "category": "BEBIDAS", "descripcion": "CERVEZA CUSQUEÑA DORADA x 6", "unidad": "PQT", "itemsPerUnit": 6 },
    { "category": "BEBIDAS", "descripcion": "CERVEZA CUSQUEÑA NEGRA x 6", "unidad": "PQT", "itemsPerUnit": 6 },
    { "category": "BEBIDAS", "descripcion": "CERVEZA CUSQUEÑA TRIGO x 6", "unidad": "PQT", "itemsPerUnit": 6 },
    { "category": "BEBIDAS", "descripcion": "CERVEZA PILSEN x 6", "unidad": "PQT", "itemsPerUnit": 6 },
    { "category": "BEBIDAS", "descripcion": "GASEOSA COCA COLA DE 1 LITRO x 4", "unidad": "PQT", "itemsPerUnit": 4 },
    { "category": "BEBIDAS", "descripcion": "GASEOSA COCA COLA DE 1.5 LITRO x 6", "unidad": "PQT", "itemsPerUnit": 6 },
    { "category": "BEBIDAS", "descripcion": "GASEOSA COCA COLA DE 1/2 LITRO x 12", "unidad": "PQT", "itemsPerUnit": 12 },
    { "category": "BEBIDAS", "descripcion": "GASEOSA FANTA DE 1/2 LITRO x 12", "unidad": "PQT", "itemsPerUnit": 12 },
    { "category": "BEBIDAS", "descripcion": "GASEOSA INCA KOLA DE 1 LITRO x 4", "unidad": "PQT", "itemsPerUnit": 4 },
    { "category": "BEBIDAS", "descripcion": "GASEOSA INCA KOLA DE 1.5 LITRO x 6", "unidad": "PQT", "itemsPerUnit": 6 },
    { "category": "BEBIDAS", "descripcion": "GASEOSA INCA KOLA DE 1/2 LITRO x 12", "unidad": "PQT", "itemsPerUnit": 12 },
    { "category": "BEBIDAS NATURALES", "descripcion": "ARANDANO CONGELADO", "unidad": "BOL", "itemsPerUnit": 1 },
    { "category": "BEBIDAS NATURALES", "descripcion": "CHICHA MORADA", "unidad": "BAL", "itemsPerUnit": 1 },
    { "category": "BEBIDAS NATURALES", "descripcion": "DESHIDRATADO DE LIMON", "unidad": "BOL", "itemsPerUnit": 1 },
    { "category": "BEBIDAS NATURALES", "descripcion": "DESHIDRATADO DE NARANJA", "unidad": "BOL", "itemsPerUnit": 1 },
    { "category": "BEBIDAS NATURALES", "descripcion": "DESHIDRATADO DE PIÑA", "unidad": "BOL", "itemsPerUnit": 1 },
    { "category": "BEBIDAS NATURALES", "descripcion": "FRESA CONGELADO", "unidad": "BOL", "itemsPerUnit": 1 },
    { "category": "BEBIDAS NATURALES", "descripcion": "MARACUYÁ", "unidad": "BOL", "itemsPerUnit": 1 },
    { "category": "BEBIDAS NATURALES", "descripcion": "PIÑA CONGELADO", "unidad": "BOL", "itemsPerUnit": 1 },
    { "category": "CARNES", "descripcion": "ANTICUCHO x 40", "unidad": "PAL", "itemsPerUnit": 40 },
    { "category": "CARNES", "descripcion": "BIFE x 20", "unidad": "UND", "itemsPerUnit": 20 },
    { "category": "CARNES", "descripcion": "CHORIZO x 60", "unidad": "UND", "itemsPerUnit": 60 },
    { "category": "CARNES", "descripcion": "CHULETA x 20", "unidad": "UND", "itemsPerUnit": 20 },
    { "category": "CARNES", "descripcion": "CHURRASCO x 15", "unidad": "UND", "itemsPerUnit": 15 },
    { "category": "CARNES", "descripcion": "COSTILLA x 15", "unidad": "UND", "itemsPerUnit": 15 },
    { "category": "CARNES", "descripcion": "FILETE DE PECHUGA x 30", "unidad": "UND", "itemsPerUnit": 30 },
    { "category": "CARNES", "descripcion": "LOMO X 200 GR x 20", "unidad": "UND", "itemsPerUnit": 20 },
    { "category": "CARNES", "descripcion": "MOLLEJA DE POLLO x 25", "unidad": "PORC", "itemsPerUnit": 25 },
    { "category": "CARNES", "descripcion": "MORCILLA", "unidad": "UND", "itemsPerUnit": 1 },
    { "category": "CARNES", "descripcion": "RACHI x 20", "unidad": "PORC", "itemsPerUnit": 20 },
    { "category": "CREMAS", "descripcion": "AHUMADO", "unidad": "BOL", "itemsPerUnit": 1 },
    { "category": "CREMAS", "descripcion": "ALITAS", "unidad": "BOL", "itemsPerUnit": 1 },
    { "category": "CREMAS", "descripcion": "ALIÑO DE PARRILLA", "unidad": "KG", "itemsPerUnit": 1 },
    { "category": "CREMAS", "descripcion": "ARROZ CHAUFA", "unidad": "BOL", "itemsPerUnit": 1 },
    { "category": "CREMAS", "descripcion": "CHIMICHURRI", "unidad": "KG", "itemsPerUnit": 1 },
    { "category": "CREMAS", "descripcion": "CREMA AJÍ", "unidad": "BOL", "itemsPerUnit": 1 },
    { "category": "CREMAS", "descripcion": "CREMA MAYONESA", "unidad": "BOL", "itemsPerUnit": 1 },
    { "category": "CREMAS", "descripcion": "CREMA VINAGRETA", "unidad": "BOL", "itemsPerUnit": 1 },
    { "category": "CREMAS", "descripcion": "SAL PARRILLERA PREPARADA", "unidad": "GR", "itemsPerUnit": 1 },
    { "category": "CREMAS", "descripcion": "SALSA ACEVICHADO", "unidad": "BOL", "itemsPerUnit": 1 },
    { "category": "CREMAS", "descripcion": "SALSA ANTICUCHERA", "unidad": "UND", "itemsPerUnit": 1 },
    { "category": "CREMAS", "descripcion": "SALSA BBQ LJD", "unidad": "KG", "itemsPerUnit": 1 },
    { "category": "CREMAS", "descripcion": "SALSA DE ORÉGANO X 250", "unidad": "GR", "itemsPerUnit": 1 },
    { "category": "CREMAS", "descripcion": "SALSA PICANTE AJI LIMO", "unidad": "KG", "itemsPerUnit": 1 },
    { "category": "CREMAS", "descripcion": "TEQUEÑOS", "unidad": "BOL", "itemsPerUnit": 1 },
    { "category": "DESCARTABLE", "descripcion": "BOLSAS 12X16 x 50", "unidad": "FARDO", "itemsPerUnit": 50 },
    { "category": "DESCARTABLE", "descripcion": "BOLSAS 16X19 x 25", "unidad": "FARDO", "itemsPerUnit": 25 },
    { "category": "DESCARTABLE", "descripcion": "BOLSAS 19X20 x 25", "unidad": "FARDO", "itemsPerUnit": 25 },
    { "category": "DESCARTABLE", "descripcion": "BOLSAS 20X30 x 100", "unidad": "PQT", "itemsPerUnit": 100 },
    { "category": "DESCARTABLE", "descripcion": "BOLSAS 220 LT x 10", "unidad": "PQT", "itemsPerUnit": 10 },
    { "category": "DESCARTABLE", "descripcion": "BOLSAS 50 LT x 20", "unidad": "PQT", "itemsPerUnit": 20 },
    { "category": "DESCARTABLE", "descripcion": "BOLSAS 8X12 x 1", "unidad": "UND.", "itemsPerUnit": 1 },
    { "category": "DESCARTABLE", "descripcion": "CUCHARITAS x 100", "unidad": "PLANCHA", "itemsPerUnit": 100 },
    { "category": "DESCARTABLE", "descripcion": "CUCHILLO DESCARTABLE x 20", "unidad": "PLANCHA", "itemsPerUnit": 20 },
    { "category": "DESCARTABLE", "descripcion": "ENVASE AJICEROS x 24", "unidad": "CAJA", "itemsPerUnit": 24 },
    { "category": "DESCARTABLE", "descripcion": "ENVASE POLLERO x 8", "unidad": "CAJA", "itemsPerUnit": 8 },
    { "category": "DESCARTABLE", "descripcion": "GORROS DESCARTABLES x 100", "unidad": "CAJA", "itemsPerUnit": 100 },
    { "category": "DESCARTABLE", "descripcion": "GUANTES QUIRURGICOS", "unidad": "CAJA", "itemsPerUnit": 1 },
    { "category": "DESCARTABLE", "descripcion": "GUANTES QUIRURGICOS TALLA L x 10", "unidad": "CAJA", "itemsPerUnit": 10 },
    { "category": "DESCARTABLE", "descripcion": "GUANTES QUIRURGICOS TALLA M x 10", "unidad": "CAJA", "itemsPerUnit": 10 },
    { "category": "DESCARTABLE", "descripcion": "GUANTES QUIRURGICOS TALLA S x 10", "unidad": "CAJA", "itemsPerUnit": 10 },
    { "category": "DESCARTABLE", "descripcion": "LIGAS DE DESPACHO x 1", "unidad": "CAJA", "itemsPerUnit": 1 },
    { "category": "DESCARTABLE", "descripcion": "MONDADIENTES x 1000 und.", "unidad": "PQT", "itemsPerUnit": 1000 },
    { "category": "DESCARTABLE", "descripcion": "PALITOS DE BROCHETAS", "unidad": "PQT", "itemsPerUnit": 1 },
    { "category": "DESCARTABLE", "descripcion": "PLATOS DESCARTABLES CHICOS x 40", "unidad": "CAJA", "itemsPerUnit": 40 },
    { "category": "DESCARTABLE", "descripcion": "PLATOS DESCARTABLES GRANDES x 40", "unidad": "CAJA", "itemsPerUnit": 40 },
    { "category": "DESCARTABLE", "descripcion": "POLIGRASA", "unidad": "PQT", "itemsPerUnit": 1 },
    { "category": "DESCARTABLE", "descripcion": "REMOVEDORES x 100", "unidad": "PQT", "itemsPerUnit": 100 },
    { "category": "DESCARTABLE", "descripcion": "SERVILLETAS DOBLADAS x 24", "unidad": "PQT", "itemsPerUnit": 24 },
    { "category": "DESCARTABLE", "descripcion": "SORBETES BLANCOS x 10", "unidad": "PLANCHA", "itemsPerUnit": 10 },
    { "category": "DESCARTABLE", "descripcion": "SORBETES NEGROS x 50", "unidad": "PQT", "itemsPerUnit": 50 },
    { "category": "DESCARTABLE", "descripcion": "TAPA AJICEROS X 2400 UNID", "unidad": "PQT", "itemsPerUnit": 1 },
    { "category": "DESCARTABLE", "descripcion": "TAPER 500 ML", "unidad": "PQT", "itemsPerUnit": 1 },
    { "category": "DESCARTABLE", "descripcion": "TAPER ENSALADA DE CUARTO 1/2 Lt. x 10", "unidad": "PLANCHA", "itemsPerUnit": 10 },
    { "category": "DESCARTABLE", "descripcion": "TAPER ENSALADA DE MEDIO x 10", "unidad": "CAJA", "itemsPerUnit": 10 },
    { "category": "DESCARTABLE", "descripcion": "TAPER ENSALADA DE POLLO 1 Lt. x 8", "unidad": "PLANCHA", "itemsPerUnit": 8 },
    { "category": "DESCARTABLE", "descripcion": "TENEDORES DESCARTABLES x 40", "unidad": "PLANCHA", "itemsPerUnit": 40 },
    { "category": "DESCARTABLE", "descripcion": "VASOS DESCARTABLES x 60", "unidad": "CAJA", "itemsPerUnit": 60 },
    { "category": "HORNO", "descripcion": "CARBÓN", "unidad": "KG", "itemsPerUnit": 1 },
    { "category": "HORNO", "descripcion": "LEÑA", "unidad": "KG", "itemsPerUnit": 1 },
    { "category": "HORNO", "descripcion": "PAPA PROCESADA", "unidad": "KG", "itemsPerUnit": 1 },
    { "category": "HORNO", "descripcion": "POLLO A LA BRASA", "unidad": "UND", "itemsPerUnit": 1 },
    { "category": "HORNO", "descripcion": "LIGAS DE POLLO X 1000", "unidad": "UND", "itemsPerUnit": 1000 },
    { "category": "LICORES", "descripcion": "ALGARROBINA", "unidad": "BOT", "itemsPerUnit": 1 },
    { "category": "LICORES", "descripcion": "AMARGO DE ANGOSTURA", "unidad": "BOT", "itemsPerUnit": 1 },
    { "category": "LICORES", "descripcion": "CREMA DE COCO", "unidad": "BOT", "itemsPerUnit": 1 },
    { "category": "LICORES", "descripcion": "CREMA DE MENTA", "unidad": "BOT", "itemsPerUnit": 1 },
    { "category": "LICORES", "descripcion": "EVERVESS x 4", "unidad": "PQT", "itemsPerUnit": 4 },
    { "category": "LICORES", "descripcion": "JARABE DE GOMA", "unidad": "BOT", "itemsPerUnit": 1 },
    { "category": "LICORES", "descripcion": "JARABE DE GRANDINA", "unidad": "BOT", "itemsPerUnit": 1 },
    { "category": "LICORES", "descripcion": "JUGO DE NARANJA", "unidad": "UND", "itemsPerUnit": 1 },
    { "category": "LICORES", "descripcion": "JUGO DE PIÑA", "unidad": "UND", "itemsPerUnit": 1 },
    { "category": "LICORES", "descripcion": "LICOR DE CACAO", "unidad": "BOT", "itemsPerUnit": 1 },
    { "category": "LICORES", "descripcion": "MARRASQUINO", "unidad": "UND", "itemsPerUnit": 1 },
    { "category": "LICORES", "descripcion": "PISCO DAMAJUANA", "unidad": "BOT", "itemsPerUnit": 1 },
    { "category": "LICORES", "descripcion": "RON BLANCO", "unidad": "BOT", "itemsPerUnit": 1 },
    { "category": "LICORES", "descripcion": "RON RUBIO", "unidad": "BOT", "itemsPerUnit": 1 },
    { "category": "LICORES", "descripcion": "VINO BLANCO (gato negro)", "unidad": "UND", "itemsPerUnit": 1 },
    { "category": "LICORES", "descripcion": "VINO INTIKALPA MALBEC", "unidad": "BOT", "itemsPerUnit": 1 },
    { "category": "LICORES", "descripcion": "VINO PEDRAS NEGRAS", "unidad": "BOT", "itemsPerUnit": 1 },
    { "category": "LICORES", "descripcion": "VINO QUEIROLO BORGOÑA", "unidad": "BOT", "itemsPerUnit": 1 },
    { "category": "LICORES", "descripcion": "VINO QUEIROLO MAGDALENA", "unidad": "BOT", "itemsPerUnit": 1 },
    { "category": "LICORES", "descripcion": "VINO TACAMA ROSÉ", "unidad": "BOT", "itemsPerUnit": 1 },
    { "category": "LIMPIEZA", "descripcion": "DETERGENTE", "unidad": "SACO", "itemsPerUnit": 1 },
    { "category": "LIMPIEZA", "descripcion": "ESCOBA DE MADERA", "unidad": "UND", "itemsPerUnit": 1 },
    { "category": "LIMPIEZA", "descripcion": "ESCOBA DE PARRILLA", "unidad": "UND", "itemsPerUnit": 1 },
    { "category": "LIMPIEZA", "descripcion": "ESCOBA DE PLÁSTICO", "unidad": "UND", "itemsPerUnit": 1 },
    { "category": "LIMPIEZA", "descripcion": "ESPONJA DUO x 7", "unidad": "CAJA", "itemsPerUnit": 7 },
    { "category": "LIMPIEZA", "descripcion": "ESPONJA MÁQUINA x 7", "unidad": "CAJA", "itemsPerUnit": 7 },
    { "category": "LIMPIEZA", "descripcion": "ESPONJA VERDE x 7", "unidad": "CAJA", "itemsPerUnit": 7 },
    { "category": "LIMPIEZA", "descripcion": "JALADOR", "unidad": "UND", "itemsPerUnit": 1 },
    { "category": "LIMPIEZA", "descripcion": "LIMPIAVIDRIOS", "unidad": "UND", "itemsPerUnit": 1 },
    { "category": "LIMPIEZA", "descripcion": "MATAMOSCAS", "unidad": "UND", "itemsPerUnit": 1 },
    { "category": "LIMPIEZA", "descripcion": "RECOGEDOR", "unidad": "UND", "itemsPerUnit": 1 },
    { "category": "LIMPIEZA", "descripcion": "SECADORES", "unidad": "DOCENA", "itemsPerUnit": 1 },
    { "category": "LIMPIEZA", "descripcion": "TOALLA DE MANO", "unidad": "DOCENA", "itemsPerUnit": 1 },
    { "category": "LIMPIEZA", "descripcion": "TRAPEADOR", "unidad": "DOCENA", "itemsPerUnit": 1 },
    { "category": "POSTRE", "descripcion": "CREMA VOLTEADA", "unidad": "UND", "itemsPerUnit": 1 },
    { "category": "POSTRE", "descripcion": "DERRUMBADO DE FRUTOS ROJOS", "unidad": "UND", "itemsPerUnit": 1 },
    { "category": "POSTRE", "descripcion": "DERRUMBADO DE LÚCUMA", "unidad": "UND", "itemsPerUnit": 1 },
    { "category": "POSTRE", "descripcion": "MOUSE DE CHOCOLATE", "unidad": "UND", "itemsPerUnit": 1 },
    { "category": "POSTRE", "descripcion": "POSTRES CUMPLEAÑOS", "unidad": "UND", "itemsPerUnit": 1 },
    { "category": "POSTRE", "descripcion": "TORTA DE CHOCOLATE", "unidad": "UND", "itemsPerUnit": 1 },
    { "category": "POSTRE", "descripcion": "TRES LECHES", "unidad": "UND", "itemsPerUnit": 1 },
    { "category": "VERDURAS", "descripcion": "AJI AMARILLO", "unidad": "KILO", "itemsPerUnit": 1 },
    { "category": "VERDURAS", "descripcion": "AJI LIMO", "unidad": "KILO", "itemsPerUnit": 1 },
    { "category": "VERDURAS", "descripcion": "AJI PANCA", "unidad": "KILO", "itemsPerUnit": 1 },
    { "category": "VERDURAS", "descripcion": "AJO", "unidad": "KG", "itemsPerUnit": 1 },
    { "category": "VERDURAS", "descripcion": "ALVERJA", "unidad": "KILO", "itemsPerUnit": 1 },
    { "category": "VERDURAS", "descripcion": "BETERRAGA", "unidad": "ATADO", "itemsPerUnit": 1 },
    { "category": "VERDURAS", "descripcion": "BRÓCOLI", "unidad": "UND", "itemsPerUnit": 1 },
    { "category": "VERDURAS", "descripcion": "CARAMBOLA", "unidad": "KILO", "itemsPerUnit": 1 },
    { "category": "VERDURAS", "descripcion": "CEBOLLA BLANCA", "unidad": "KG", "itemsPerUnit": 1 },
    { "category": "VERDURAS", "descripcion": "CEBOLLA CHINA", "unidad": "ATADO", "itemsPerUnit": 1 },
    { "category": "VERDURAS", "descripcion": "CEBOLLA CHINA PROCESADA", "unidad": "PQT", "itemsPerUnit": 1 },
    { "category": "VERDURAS", "descripcion": "CEBOLLA ROJA", "unidad": "KILO", "itemsPerUnit": 1 },
    { "category": "VERDURAS", "descripcion": "CHAMPIGÑON", "unidad": "BANDEJA", "itemsPerUnit": 1 },
    { "category": "VERDURAS", "descripcion": "CHOCLO", "unidad": "UND", "itemsPerUnit": 1 },
    { "category": "VERDURAS", "descripcion": "CULANTRO", "unidad": "UNIDAD", "itemsPerUnit": 1 },
    { "category": "VERDURAS", "descripcion": "ESPINACA", "unidad": "ATADO", "itemsPerUnit": 1 },
    { "category": "VERDURAS", "descripcion": "HIERBA LUISA", "unidad": "ATADO", "itemsPerUnit": 1 },
    { "category": "VERDURAS", "descripcion": "HUACATAY", "unidad": "ATADO", "itemsPerUnit": 1 },
    { "category": "VERDURAS", "descripcion": "HUEVO DE CODORNIZ", "unidad": "UND", "itemsPerUnit": 1 },
    { "category": "VERDURAS", "descripcion": "KION", "unidad": "KILO", "itemsPerUnit": 1 },
    { "category": "VERDURAS", "descripcion": "LECHUGA AMERICANA", "unidad": "DOC", "itemsPerUnit": 12 },
    { "category": "VERDURAS", "descripcion": "LECHUGA CRESPA", "unidad": "DOC", "itemsPerUnit": 12 },
    { "category": "VERDURAS", "descripcion": "LIMON", "unidad": "KG", "itemsPerUnit": 1 },
    { "category": "VERDURAS", "descripcion": "MAIZ MORADO", "unidad": "KILO", "itemsPerUnit": 1 },
    { "category": "VERDURAS", "descripcion": "MANZANA", "unidad": "KG", "itemsPerUnit": 1 },
    { "category": "VERDURAS", "descripcion": "MANZANA AGUA", "unidad": "KILO", "itemsPerUnit": 1 },
    { "category": "VERDURAS", "descripcion": "MARACUYA", "unidad": "KILO", "itemsPerUnit": 1 },
    { "category": "VERDURAS", "descripcion": "MEMBRILLO", "unidad": "KILO", "itemsPerUnit": 1 },
    { "category": "VERDURAS", "descripcion": "MENTA", "unidad": "ATADO", "itemsPerUnit": 1 },
    { "category": "VERDURAS", "descripcion": "MUÑA", "unidad": "ATADO", "itemsPerUnit": 1 },
    { "category": "VERDURAS", "descripcion": "NARANJA", "unidad": "KG", "itemsPerUnit": 1 },
    { "category": "VERDURAS", "descripcion": "OREGANO", "unidad": "ATADO", "itemsPerUnit": 1 },
    { "category": "VERDURAS", "descripcion": "PALTA", "unidad": "KG", "itemsPerUnit": 1 },
    { "category": "VERDURAS", "descripcion": "PAPA BLANCA", "unidad": "KG", "itemsPerUnit": 1 },
    { "category": "VERDURAS", "descripcion": "PAPA YUNGAY", "unidad": "KILO", "itemsPerUnit": 1 },
    { "category": "VERDURAS", "descripcion": "PECANA", "unidad": "KG", "itemsPerUnit": 1 },
    { "category": "VERDURAS", "descripcion": "PEPINO", "unidad": "KG", "itemsPerUnit": 12 },
    { "category": "VERDURAS", "descripcion": "PEREJIL", "unidad": "ATADO", "itemsPerUnit": 1 },
    { "category": "VERDURAS", "descripcion": "PIMIENTO", "unidad": "KG", "itemsPerUnit": 1 },
    { "category": "VERDURAS", "descripcion": "PIÑA", "unidad": "UND", "itemsPerUnit": 1 },
    { "category": "VERDURAS", "descripcion": "QUESO", "unidad": "UNIDAD", "itemsPerUnit": 1 },
    { "category": "VERDURAS", "descripcion": "ROMERO", "unidad": "ATADO", "itemsPerUnit": 1 },
    { "category": "VERDURAS", "descripcion": "TOMATE", "unidad": "KG", "itemsPerUnit": 1 },
    { "category": "VERDURAS", "descripcion": "VAINITA", "unidad": "KG", "itemsPerUnit": 1 },
    { "category": "VERDURAS", "descripcion": "WANTAN", "unidad": "KILO", "itemsPerUnit": 1 },
    { "category": "VERDURAS", "descripcion": "ZANAHORIA", "unidad": "KG", "itemsPerUnit": 1 }
].sort((a, b) => {
    if (a.category < b.category) return -1;
    if (a.category > b.category) return 1;
    if (a.descripcion < b.descripcion) return -1;
    if (a.descripcion > b.descripcion) return 1;
    return 0;
});

const baseProducts = [
    { id: 'ab1', category: 'ABARROTES', name: 'Aceite de Oliva', u_med: 'BOT', min_stocks: { "Villa 1": 10 , "Villa 2": 5, "Manchay": 2 } },
    { id: 'ab8', category: 'ABARROTES', name: 'Kétchup Granel X 10 KG', u_med: 'CAJA', min_stocks: { "Villa 1": 10  , "Villa 2": 5, "Manchay": 14 } },
    { id: 'ab9', category: 'ABARROTES', name: 'Kétchup Sachet', u_med: 'CAJA', min_stocks: { "Villa 1": 10, "Villa 2": 5, "Manchay": 44 } },
    { id: 'ab10', category: 'ABARROTES', name: 'Leche Evaporada', u_med: 'UND', min_stocks: { "Villa 1": 15, "Villa 2": 5, "Manchay": 24 } },
    { id: 'ab12', category: 'ABARROTES', name: 'Mostaza Granel X 10 KG', u_med: 'CAJA', min_stocks: { "Villa 1": 39, "Villa 2": 5, "Manchay": 39 } },
    { id: 'ab13', category: 'ABARROTES', name: 'Mostaza Sachet', u_med: 'CAJA', min_stocks: { "Villa 1": 42, "Villa 2": 5, "Manchay": 42 } },
    { id: 'ab14', category: 'ABARROTES', name: 'Pimienta Negra', u_med: 'FRASCO', min_stocks: { "Villa 1": 24, "Villa 2": 5, "Manchay": 24 } },
    { id: 'ab15', category: 'ABARROTES', name: 'Piña en Conserva', u_med: 'LATA', min_stocks: { "Villa 1": 24, "Villa 2": 5, "Manchay": 24 } },
    { id: 'ab3', category: 'ABARROTES', name: 'Arroz', u_med: 'SACO', min_stocks: { "Villa 1": 3, "Villa 2": 5, "Manchay": 3 } },
    { id: 'ab4', category: 'ABARROTES', name: 'Azúcar Blanca', u_med: 'SACO', min_stocks: { "Villa 1": 5, "Villa 2": 5, "Manchay": 5 } },
    { id: 'ab5', category: 'ABARROTES', name: 'Azúcar Rubia', u_med: 'SACO', min_stocks: { "Villa 1": 3, "Villa 2": 3, "Manchay": 3 } },
    { id: 'ab11', category: 'ABARROTES', name: 'Manzanilla', u_med: 'CAJA', min_stocks: { "Villa 1": 9, "Villa 2": 9, "Manchay": 9 } },
    { id: 'ab17', category: 'ABARROTES', name: 'Té', u_med: 'CAJA', min_stocks: { "Villa 1": 2, "Villa 2": 2, "Manchay": 2 } },
    { id: 'ab2', category: 'ABARROTES', name: 'Anís', u_med: 'CAJA', min_stocks: { "Villa 1": 2, "Villa 2": 2, "Manchay": 2 } },
    { id: 'ab6', category: 'ABARROTES', name: 'Café Granel', u_med: 'BOLSA', min_stocks: { "Villa 1": 2, "Villa 2": 2, "Manchay": 2 } },
    { id: 'ab7', category: 'ABARROTES', name: 'Fósforo', u_med: 'PQT', min_stocks: { "Villa 1": 2, "Villa 2": 2, "Manchay": 2 } },
    { id: 'ab16', category: 'ABARROTES', name: 'Sal', u_med: 'SACO', min_stocks: { "Villa 1": 2, "Villa 2": 2, "Manchay": 2 } },
    { id: 'be1', category: 'BEBIDAS', name: 'Gaseosa Inca Kola De 1.5 Litro X 6', u_med: 'PQT', min_stocks: { "Villa 1": 12, "Villa 2": 6, "Manchay": 12 } },
    { id: 'be2', category: 'BEBIDAS', name: 'Gaseosa Inca Kola De 1 Litro X 4', u_med: 'PQT', min_stocks: { "Villa 1": 12, "Villa 2": 6, "Manchay": 12 } },
    { id: 'be3', category: 'BEBIDAS', name: 'Gaseosa Inca Kola De 1/2 Litro X 12', u_med: 'PQT', min_stocks: { "Villa 1": 12, "Villa 2": 6, "Manchay": 12 } },
    { id: 'be4', category: 'BEBIDAS', name: 'Gaseosa Coca Cola De 1.5 Litro X 6', u_med: 'PQT', min_stocks: { "Villa 1": 12, "Villa 2": 6, "Manchay": 12 } },
    { id: 'be5', category: 'BEBIDAS', name: 'Gaseosa Coca Cola De 1 Litro X 4', u_med: 'PQT', min_stocks: { "Villa 1": 12, "Villa 2": 6, "Manchay": 12 } },
    { id: 'be6', category: 'BEBIDAS', name: 'Gaseosa Coca Cola De 1/2 Litro X 12', u_med: 'PQT', min_stocks: { "Villa 1": 12, "Villa 2": 6, "Manchay": 12 } },
    { id: 'be7', category: 'BEBIDAS', name: 'Cerveza Pilsen X 6', u_med: 'PQT', min_stocks: { "Villa 1": 15, "Villa 2": 8, "Manchay": 15 } },
    { id: 'be8', category: 'BEBIDAS', name: 'Cerveza Cusqueña Negra X 6', u_med: 'PQT', min_stocks: { "Villa 1": 15, "Villa 2": 8, "Manchay": 15 } },
    { id: 'be9', category: 'BEBIDAS', name: 'Cerveza Cusqueña Dorada X 6', u_med: 'PQT', min_stocks: { "Villa 1": 15, "Villa 2": 8, "Manchay": 15 } },
    { id: 'be10', category: 'BEBIDAS', name: 'Cerveza Cusqueña Trigo X 6', u_med: 'PQT', min_stocks: { "Villa 1": 15, "Villa 2": 8, "Manchay": 15 } },
    { id: 'be11', category: 'BEBIDAS', name: 'Agua Mineral 3 Litros X 4', u_med: 'PQT', min_stocks: { "Villa 1": 10, "Villa 2": 5, "Manchay": 10 } },
    { id: 'be12', category: 'BEBIDAS', name: 'Agua San Luis Con Gas 600 Ml X 15', u_med: 'PQT', min_stocks: { "Villa 1": 10, "Villa 2": 5, "Manchay": 10 } },
    { id: 'be13', category: 'BEBIDAS', name: 'Agua San Luis Sin Gas 600 Ml X 15', u_med: 'PQT', min_stocks: { "Villa 1": 10, "Villa 2": 5, "Manchay": 10 } },
    { id: 'li1', category: 'LIMPIEZA', name: 'Detergente', u_med: 'SACO', min_stocks: { "Villa 1": 16, "Villa 2": 5, "Manchay": 20 } },
    { id: 'li4', category: 'LIMPIEZA', name: 'Escoba de Plástico', u_med: 'UND', min_stocks: { "Villa 1": 4, "Villa 2": 5, "Manchay": 6 } },
    { id: 'li5', category: 'LIMPIEZA', name: 'Esponja Dúo', u_med: 'CAJA', min_stocks: { "Villa 1": 4, "Villa 2": 5, "Manchay": 6 } },
    { id: 'li6', category: 'LIMPIEZA', name: 'Esponja Máquina', u_med: 'CAJA', min_stocks: { "Villa 1": 5, "Villa 2": 5, "Manchay": 5 } },
    { id: 'li7', category: 'LIMPIEZA', name: 'Esponja Verde', u_med: 'CAJA', min_stocks: { "Villa 1": 4, "Villa 2": 5, "Manchay": 4 } },
    { id: 'li9', category: 'LIMPIEZA', name: 'Limpiavidrios', u_med: 'UND', min_stocks: { "Villa 1": 4, "Villa 2": 4, "Manchay": 4 } },
    { id: 'li13', category: 'LIMPIEZA', name: 'Secadores', u_med: 'DOCENA', min_stocks: { "Villa 1": 4, "Villa 2": 4, "Manchay": 4 } },
    { id: 'li14', category: 'LIMPIEZA', name: 'Toalla de Mano Microfibra', u_med: 'DOCENA', min_stocks: { "Villa 1": 2, "Villa 2": 2, "Manchay": 2 } },
    { id: 'li15', category: 'LIMPIEZA', name: 'Trapeador', u_med: 'DOCENA', min_stocks: { "Villa 1": 3, "Villa 2": 3, "Manchay": 3 } },
    { id: 'li2', category: 'LIMPIEZA', name: 'Escoba de Madera', u_med: 'UND', min_stocks: { "Villa 1": 4, "Villa 2": 4, "Manchay": 4 } },
    { id: 'li3', category: 'LIMPIEZA', name: 'Escoba de Parrilla', u_med: 'UND', min_stocks: { "Villa 1": 6, "Villa 2": 6, "Manchay": 6 } },
    { id: 'li8', category: 'LIMPIEZA', name: 'Jalador', u_med: 'UND', min_stocks: { "Villa 1": 2, "Villa 2": 2, "Manchay": 2 } },
    { id: 'li10', category: 'LIMPIEZA', name: 'Matamoscas', u_med: 'UND', min_stocks: { "Villa 1": 5, "Villa 2": 5, "Manchay": 5 } },
    { id: 'li11', category: 'LIMPIEZA', name: 'Recogedor', u_med: 'UND', min_stocks: { "Villa 1": 6, "Villa 2": 6, "Manchay": 6 } },
    { id: 'li12', category: 'LIMPIEZA', name: 'Renovador de Madera', u_med: 'UND', min_stocks: { "Villa 1": 2, "Villa 2": 2, "Manchay": 2 } },
    { id: 'd16', category: 'DESCARTABLES', name: 'Guantes Quirúrgicos Talla L', u_med: 'CAJA', min_stocks: { "Villa 1": 12, "Villa 2": 5, "Manchay": 12 } },
    { id: 'd19', category: 'DESCARTABLES', name: 'Ligas de Despacho x 1 libra', u_med: 'CAJA', min_stocks: { "Villa 1": 13, "Villa 2": 5, "Manchay": 13 } },
    { id: 'd11', category: 'DESCARTABLES', name: 'Envase Ajiceros x 24 paq.', u_med: 'CAJA', min_stocks: { "Villa 1": 13, "Villa 2": 5, "Manchay": 13 } },
    { id: 'd12', category: 'DESCARTABLES', name: 'Envase Pollero x 8 paq.', u_med: 'CAJA', min_stocks: { "Villa 1": 16, "Villa 2": 5, "Manchay": 16 } },
    { id: 'd23', category: 'DESCARTABLES', name: 'Platos Descartables Grandes', u_med: 'CAJA', min_stocks: { "Villa 1": 9, "Villa 2": 5, "Manchay": 9 } },
    { id: 'd29', category: 'DESCARTABLES', name: 'Taper Ensalada de Cuarto 1/2 Lt.', u_med: 'PLANCHA', min_stocks: { "Villa 1": 9, "Villa 2": 5, "Manchay": 9 } },
    { id: 'd31', category: 'DESCARTABLES', name: 'Taper Ensalada de Pollo 1 Lt.', u_med: 'PLANCHA', min_stocks: { "Villa 1": 16, "Villa 2": 16, "Manchay": 16 } },
    { id: 'd1', category: 'DESCARTABLES', name: 'Bolsas 12x16 x 50 pqt.', u_med: 'FARDO', min_stocks: { "Villa 1": 5, "Villa 2": 5, "Manchay": 5 } },
    { id: 'd2', category: 'DESCARTABLES', name: 'Bolsas 16x19 x 25 pqt.', u_med: 'FARDO', min_stocks: { "Villa 1": 6, "Villa 2": 6, "Manchay": 6 } },
    { id: 'd3', category: 'DESCARTABLES', name: 'Bolsas 19x20 x 25 pqt.', u_med: 'FARDO', min_stocks: { "Villa 1": 4, "Villa 2": 4, "Manchay": 4 } },
    { id: 'd4', category: 'DESCARTABLES', name: 'Bolsas 20x30 x 100 und.', u_med: 'PQT', min_stocks: { "Villa 1": 3, "Villa 2": 3, "Manchay": 3 } },
    { id: 'd5', category: 'DESCARTABLES', name: 'Bolsas 50 Lt x 10 pqt.', u_med: 'PQT', min_stocks: { "Villa 1": 4, "Villa 2": 4, "Manchay": 4 } },
    { id: 'd6', category: 'DESCARTABLES', name: 'Bolsas 220 Lt x 10 pqt.', u_med: 'PQT', min_stocks: { "Villa 1": 3, "Villa 2": 3, "Manchay": 3 } },
    { id: 'd7', category: 'DESCARTABLES', name: 'Bolsas 50 Lt x 20 pqt.', u_med: 'PQT', min_stocks: { "Villa 1": 4, "Villa 2": 4, "Manchay": 4 } },
    { id: 'd13', category: 'DESCARTABLES', name: 'Gorros Descartables x 100 und.', u_med: 'CAJA', min_stocks: { "Villa 1": 7, "Villa 2": 7, "Manchay": 7 } },
    { id: 'd14', category: 'DESCARTABLES', name: 'Guantes Quirúrgicos Talla S', u_med: 'CAJA', min_stocks: { "Villa 1": 3, "Villa 2": 3, "Manchay": 3 } },
    { id: 'd15', category: 'DESCARTABLES', name: 'Guantes Quirúrgicos Talla M', u_med: 'CAJA', min_stocks: { "Villa 1": 4, "Villa 2": 4, "Manchay": 4 } },
    { id: 'd22', category: 'DESCARTABLES', name: 'Platos Descartables Chicos', u_med: 'CAJA', min_stocks: { "Villa 1": 4, "Villa 2": 4, "Manchay": 4 } },
    { id: 'd26', category: 'DESCARTABLES', name: 'Servilletas Dobladas x 24 pqt.', u_med: 'PQT', min_stocks: { "Villa 1": 4, "Villa 2": 4, "Manchay": 4 } },
    { id: 'd27', category: 'DESCARTABLES', name: 'Sorbetes Blancos x 10 pqt.', u_med: 'PLANCHA', min_stocks: { "Villa 1": 2, "Villa 2": 2, "Manchay": 2 } },
    { id: 'd30', category: 'DESCARTABLES', name: 'Taper Ensalada de Medio x 10 pqt.', u_med: 'CAJA', min_stocks: { "Villa 1": 6, "Villa 2": 6, "Manchay": 6 } },
    { id: 'd8', category: 'DESCARTABLES', name: 'Bolsas 8x12 x 1 rollo', u_med: 'UND.', min_stocks: { "Villa 1": 1, "Villa 2": 1, "Manchay": 1 } },
    { id: 'd9', category: 'DESCARTABLES', name: 'Cucharitas x 100 paq.', u_med: 'PLANCHA', min_stocks: { "Villa 1": 1, "Villa 2": 1, "Manchay": 1 } },
    { id: 'd10', category: 'DESCARTABLES', name: 'Cuchillo Descartable x 20 pqt.', u_med: 'PLANCHA', min_stocks: { "Villa 1": 1, "Villa 2": 1, "Manchay": 1 } },
    { id: 'd17', category: 'DESCARTABLES', name: 'Guantes de Latex M', u_med: 'CAJA', min_stocks: { "Villa 1": 1, "Villa 2": 1, "Manchay": 1 } },
    { id: 'd18', category: 'DESCARTABLES', name: 'Guantes de Latex S', u_med: 'CAJA', min_stocks: { "Villa 1": 1, "Villa 2": 1, "Manchay": 1 } },
    { id: 'd20', category: 'DESCARTABLES', name: 'Mondadientes x 1000 und.', u_med: 'PQT', min_stocks: { "Villa 1": 1, "Villa 2": 1, "Manchay": 1 } },
    { id: 'd21', category: 'DESCARTABLES', name: 'Palitos de Brochetas', u_med: 'PQT', min_stocks: { "Villa 1": 1, "Villa 2": 1, "Manchay": 1 } },
    { id: 'd24', category: 'DESCARTABLES', name: 'Poligrasa x 500 laminas', u_med: 'PQT', min_stocks: { "Villa 1": 9, "Villa 2": 9, "Manchay": 9 } },
    { id: 'd25', category: 'DESCARTABLES', name: 'Removedores x 100 und.', u_med: 'PQT', min_stocks: { "Villa 1": 2, "Villa 2": 2, "Manchay": 2 } },
    { id: 'd28', category: 'DESCARTABLES', name: 'Sorbetes Negros x 50 und.', u_med: 'PQT', min_stocks: { "Villa 1": 1, "Villa 2": 1, "Manchay": 1 } },
    { id: 'd32', category: 'DESCARTABLES', name: 'Tenedores Descartables x 40 pqt.', u_med: 'PLANCHA', min_stocks: { "Villa 1": 1, "Villa 2": 1, "Manchay": 1 } },
    { id: 'd33', category: 'DESCARTABLES', name: 'Vasos Descartables x 60 pqt.', u_med: 'CAJA', min_stocks: { "Villa 1": 1, "Villa 2": 1, "Manchay": 1 } },
    { id: 'l3', category: 'LICORES', name: 'Crema de Coco', u_med: 'BOT', min_stocks: { "Villa 1": 24, "Villa 2": 24, "Manchay": 24 } },
    { id: 'l18', category: 'LICORES', name: 'Vino Rosé', u_med: 'BOT', min_stocks: { "Villa 1": 48, "Villa 2": 30, "Manchay": 48 } },
    { id: 'l4', category: 'LICORES', name: 'Crema de Menta', u_med: 'BOT', min_stocks: { "Villa 1": 12, "Villa 2": 12, "Manchay": 12 } },
    { id: 'l7', category: 'LICORES', name: 'Jarabe de Granadina', u_med: 'BOT', min_stocks: { "Villa 1": 15, "Villa 2": 15, "Manchay": 15 } },
    { id: 'l10', category: 'LICORES', name: 'Licor de Cacao', u_med: 'BOT', min_stocks: { "Villa 1": 13, "Villa 2": 13, "Manchay": 13 } },
    { id: 'l11', category: 'LICORES', name: 'Marrasquino', u_med: 'UND', min_stocks: { "Villa 1": 14, "Villa 2": 14, "Manchay": 14 } },
    { id: 'l1', category: 'LICORES', name: 'Algarrobina', u_med: 'BOT', min_stocks: { "Villa 1": 8, "Villa 2": 8, "Manchay": 8 } },
    { id: 'l2', category: 'LICORES', name: 'Amargo de Angostura', u_med: 'BOT', min_stocks: { "Villa 1": 12, "Villa 2": 12, "Manchay": 12 } },
    { id: 'l8', category: 'LICORES', name: 'Jugo de Naranja', u_med: 'UND', min_stocks: { "Villa 1": 12, "Villa 2": 12, "Manchay": 12 } },
    { id: 'l9', category: 'LICORES', name: 'Jugo de Piña', u_med: 'UND', min_stocks: { "Villa 1": 9, "Villa 2": 9, "Manchay": 9 } },
    { id: 'l5', category: 'LICORES', name: 'Evervess', u_med: 'BOT', min_stocks: { "Villa 1": 2, "Villa 2": 2, "Manchay": 2 } },
    { id: 'l6', category: 'LICORES', name: 'Jarabe de Goma', u_med: 'BOT', min_stocks: { "Villa 1": 2, "Villa 2": 2, "Manchay": 2 } },
    { id: 'l12', category: 'LICORES', name: 'Pisco Damajuana', u_med: 'BOT', min_stocks: { "Villa 1": 6, "Villa 2": 6, "Manchay": 6 } },
    { id: 'l13', category: 'LICORES', name: 'Ron Blanco', u_med: 'BOT', min_stocks: { "Villa 1": 6, "Villa 2": 6, "Manchay": 6 } },
    { id: 'l14', category: 'LICORES', name: 'Vino Borgona', u_med: 'BOT', min_stocks: { "Villa 1": 24, "Villa 2": 24, "Manchay": 24 } },
    { id: 'l15', category: 'LICORES', name: 'Vino Intikalka', u_med: 'BOT', min_stocks: { "Villa 1": 2, "Villa 2": 2, "Manchay": 2 } },
    { id: 'l16', category: 'LICORES', name: 'Vino Magdalena', u_med: 'BOT', min_stocks: { "Villa 1": 28, "Villa 2": 20, "Manchay": 28 } },
    { id: 'l17', category: 'LICORES', name: 'Vino Piedras Negras', u_med: 'BOT', min_stocks: { "Villa 1": 4, "Villa 2": 4, "Manchay": 4 } },
];